---
# Based on https://www.npmjs.com/package/rpio needs

- name: Enable sound
  become: yes
  file:
    path: /etc/udev/rules.d/20-gpiomem.rules
    owner: root
    group: root
    mode: "0644"
    state: touch

- name: Enable sound
  become: yes
  lineinfile:
    path: /boot/firmware/usercfg.txt
    line: "dtparam=audio=on"
