---
- name: Download the nodesource script
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/nodesource.sh

- name: Execute the nodesource script
  become: yes
  command: bash /tmp/nodesource.sh

- name: Install nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: Remove the nodesource script
  file:
    path: /tmp/nodesource.sh
    state: absent
