---
- name: create systemd service
  become: yes
  template:
    owner: root
    group: root
    mode: 0644
    src: discloakroom.service.j2
    dest: /etc/systemd/system/discloakroom.service

- name: restart discloakroom
  become: yes
  service:
    name: discloakroom
    enabled: yes
    state: restarted
